<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>StArray.ModManager.Windows</RootNamespace>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugType>embedded</DebugType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StArray.ModManager\StArray.ModManager.csproj" />
    <ProjectReference Include="..\StArray.ModManager.Analyzer\StArray.ModManager.Analyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="dlls\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

  <Target Name="BuildNativeDll" BeforeTargets="BeforeBuild" Condition="'$(BuildNativeDll)' != 'false'">
    <Exec Command="cmake -B &quot;$(ProjectDir)Native\build&quot; -G &quot;Ninja&quot; -DCMAKE_BUILD_TYPE=$(Configuration)"
          WorkingDirectory="$(ProjectDir)Native" />
    <Exec Command="cmake --build &quot;$(ProjectDir)Native\build&quot;"
          WorkingDirectory="$(ProjectDir)Native" />
  </Target>

</Project>
