using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace StArray.ModManager.SourceGenerator;

[Generator]
public class UnmanagedStubGenerator : IIncrementalGenerator
{
    private const string TypeAttrName = "StArray.ModManager.RuntimeAbstractions.UnmanagedTypeAttribute";
    private const string MemberAttrName = "StArray.ModManager.RuntimeAbstractions.UnmanagedMemberAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsClassWithAttributes(node),
                transform: static (ctx, _) => GetClassInfo(ctx))
            .Where(static info => info != null)!;

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(classes.Collect()),
            static (spc, t) => Generate(spc, t.Left, t.Right));
    }

    private static bool IsClassWithAttributes(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax cds &&
               cds.AttributeLists.Count > 0 &&
               cds.Modifiers.Any(SyntaxKind.PartialKeyword);
    }

    private sealed class UnmanagedClassInfo
    {
        public string Namespace { get; set; } = "";
        public string ClassName { get; set; } = "";
        public string FullType { get; set; } = "";
        public string? Assembly { get; set; }
        public string? TypeNs { get; set; }
        public string? TypeName { get; set; }
        public bool HasBaseType { get; set; }
        public List<MemberInfo> Members { get; set; } = new();
    }

    private sealed class MemberInfo
    {
        public string MethodName { get; set; } = "";
        public string ReturnType { get; set; } = "";
        public bool IsStatic { get; set; }
        public List<(string Type, string Name)> Parameters { get; set; } = new();
    }

    private static UnmanagedClassInfo? GetClassInfo(GeneratorSyntaxContext ctx)
    {
        var cls = (ClassDeclarationSyntax)ctx.Node;
        var sem = ctx.SemanticModel;
        var sym = sem.GetDeclaredSymbol(cls);
        if (sym is null) return null;

        var typeAttr = sym.GetAttributes().FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString() == TypeAttrName);
        if (typeAttr is null) return null;

        var info = new UnmanagedClassInfo
        {
            Namespace = sym.ContainingNamespace.ToDisplayString(),
            ClassName = sym.Name,
            FullType = sym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            Assembly = typeAttr.ConstructorArguments.Length > 0
                ? typeAttr.ConstructorArguments[0].Value?.ToString() : null,
            TypeNs = typeAttr.ConstructorArguments.Length > 1
                ? typeAttr.ConstructorArguments[1].Value?.ToString() : null,
            TypeName = typeAttr.ConstructorArguments.Length > 2
                ? typeAttr.ConstructorArguments[2].Value?.ToString() : null,
            HasBaseType = sym.BaseType != null &&
                          sym.BaseType.SpecialType != SpecialType.System_Object,
        };

        foreach (var member in sym.GetMembers())
        {
            if (member is not IMethodSymbol method) continue;
            if (!method.GetAttributes().Any(a =>
                    a.AttributeClass?.ToDisplayString() == MemberAttrName)) continue;
            if (!method.IsPartialDefinition) continue;

            var mi = new MemberInfo
            {
                MethodName = method.Name,
                ReturnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                IsStatic = method.IsStatic,
                Parameters = method.Parameters.Select(p =>
                    (p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), p.Name)).ToList(),
            };
            info.Members.Add(mi);
        }

        return info.Members.Count > 0 ? info : null;
    }

    private static void Generate(SourceProductionContext spc, Compilation compilation,
        ImmutableArray<UnmanagedClassInfo> classes)
    {
        if (classes.Length == 0) return;

        foreach (var cls in classes)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8618, CS8625");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            var hasNs = !string.IsNullOrEmpty(cls.Namespace);
            if (hasNs)
            {
                sb.AppendLine($"namespace {cls.Namespace}");
                sb.AppendLine("{");
            }

            var hasStatic = cls.Members.Any(m => m.IsStatic);

            sb.AppendLine("    using global::StArray.ModManager.RuntimeAbstractions;");
            sb.AppendLine();
            sb.Append($"    public unsafe partial class {cls.ClassName}");
            if (!cls.HasBaseType)
                sb.Append(" : global::StArray.ModManager.RuntimeAbstractions.UnmanagedObject");
            sb.AppendLine();
            sb.AppendLine("    {");
            if (!cls.HasBaseType)
            {
                sb.AppendLine($"        public {cls.ClassName}(nint ptr) : base(ptr) {{ }}");
                sb.AppendLine();
            }

            if (hasStatic && cls.Assembly != null && cls.TypeName != null)
            {
                sb.AppendLine("        private static IRuntimeClass? s_resolvedClass;");
                sb.AppendLine("        private static bool s_classResolved;");
                sb.AppendLine();
                sb.AppendLine("        private static IRuntimeClass? ResolveClass()");
                sb.AppendLine("        {");
                sb.AppendLine("            if (!s_classResolved)");
                sb.AppendLine("            {");
                sb.AppendLine($"                var domain = RuntimeManager.GetDomain();");
                sb.AppendLine($"                var asm = domain?.OpenAssembly(\"{EscapeString(cls.Assembly)}\");");
                sb.AppendLine($"                s_resolvedClass = asm?.GetClass(\"{EscapeString(cls.TypeNs ?? "")}\", \"{EscapeString(cls.TypeName)}\");");
                sb.AppendLine("                s_classResolved = true;");
                sb.AppendLine("            }");
                sb.AppendLine("            return s_resolvedClass;");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            // Group members: get_/set_ → property, add_/remove_ → event, rest → method
            var membersByName = cls.Members.GroupBy(m =>
            {
                var name = m.MethodName;
                if (name.StartsWith("get_")) return name.Substring(4);
                if (name.StartsWith("set_")) return name.Substring(4);
                if (name.StartsWith("add_")) return name.Substring(4);
                if (name.StartsWith("remove_")) return name.Substring(7);
                return null;
            }).ToList();

            var processed = new HashSet<string>();

            foreach (var group in membersByName)
            {
                if (group.Key == null)
                {
                    // standalone method
                    foreach (var m in group)
                        GenerateMethod(sb, m);
                    continue;
                }

                var getter = group.FirstOrDefault(m => m.MethodName == "get_" + group.Key);
                var setter = group.FirstOrDefault(m => m.MethodName == "set_" + group.Key);
                var adder = group.FirstOrDefault(m => m.MethodName == "add_" + group.Key);
                var remover = group.FirstOrDefault(m => m.MethodName == "remove_" + group.Key);

                if (getter != null || setter != null)
                {
                    if (getter != null && setter != null)
                    {
                        // Both getter and setter
                        GenerateGetter(sb, getter);
                        GenerateSetter(sb, setter);
                        GenerateProperty(sb, group.Key, getter, setter);
                    }
                    else if (getter != null)
                    {
                        GenerateGetter(sb, getter);
                        GeneratePropertyGetOnly(sb, group.Key, getter);
                    }
                    else
                    {
                        GenerateSetter(sb, setter);
                        GeneratePropertySetOnly(sb, group.Key, setter);
                    }
                }

                // add_/remove_ 作为普通方法生成（C# event 要求委托类型，不适合 nint 指针）
                if (adder != null) GenerateMethod(sb, adder);
                if (remover != null) GenerateMethod(sb, remover);
            }

            sb.AppendLine("    }");
            if (hasNs) sb.AppendLine("}");
            sb.AppendLine();

            spc.AddSource($"Unmanaged_{cls.ClassName}.g.cs", sb.ToString());
        }
    }

    private static string AsPropertyName(string name) => char.ToUpper(name[0]) + name.Substring(1);

    private static void GenerateMethod(StringBuilder sb, MemberInfo m)
    {
        var pd = string.Join(", ", m.Parameters.Select(p => $"{SimplifyType(p.Type)} @{p.Name}"));
        var ro = m.ReturnType == "global::System.Void" ? "void" : SimplifyType(m.ReturnType);
        var rt = m.ReturnType;
        var sig = m.IsStatic ? "static " : "";

        sb.AppendLine();
        sb.AppendLine($"        public {sig}partial {ro} {m.MethodName}({pd})");
        sb.AppendLine("        {");

        if (m.Parameters.Count > 0)
        {
            sb.AppendLine($"            var args = new nint[] {{");
            for (int i = 0; i < m.Parameters.Count; i++)
            {
                var comma = i < m.Parameters.Count - 1 ? "," : "";
                sb.AppendLine($"                {MarshalParam(m.Parameters[i].Type, $"@{m.Parameters[i].Name}")}{comma}");
            }
            sb.AppendLine("            };");
        }

        if (m.IsStatic)
        {
            var argsExpr = m.Parameters.Count > 0 ? "args" : "null";
            if (rt is "void" or "global::System.Void")
            {
                sb.AppendLine($"            var cls = ResolveClass();");
                sb.AppendLine($"            if (cls == null) return;");
                sb.AppendLine($"            var method = cls.GetMethod(\"{m.MethodName}\", {m.Parameters.Count});");
                sb.AppendLine($"            method?.InvokeStatic({argsExpr});");
            }
            else
            {
                sb.AppendLine($"            var cls = ResolveClass();");
                sb.AppendLine($"            if (cls == null) return default;");
                sb.AppendLine($"            var method = cls.GetMethod(\"{m.MethodName}\", {m.Parameters.Count});");
                sb.AppendLine($"            if (method == null) return default;");
                sb.AppendLine($"            var ret = method.InvokeStatic({argsExpr});");
                sb.AppendLine($"            return {MarshalReturn(rt, "ret")};");
            }
        }
        else
        {
            if (rt is "void" or "global::System.Void")
            {
                sb.AppendLine($"            new RuntimeObject(Ptr).InvokeVoid(\"{m.MethodName}\", {m.Parameters.Count}{(m.Parameters.Count > 0 ? ", args" : "")});");
            }
            else
            {
                var call = $"new RuntimeObject(Ptr).Invoke(\"{m.MethodName}\", {m.Parameters.Count}{(m.Parameters.Count > 0 ? ", args" : "")})";
                sb.AppendLine($"            var ret = {call};");
                sb.AppendLine($"            return {MarshalReturn(rt, "ret")};");
            }
        }

        sb.AppendLine("        }");
    }

    private static void GenerateGetter(StringBuilder sb, MemberInfo m)
    {
        var rt = m.ReturnType;
        var ro = rt == "global::System.Void" ? "void" : SimplifyType(rt);
        if (ro == "void") return;
        sb.AppendLine();
        sb.AppendLine($"        public partial {ro} {m.MethodName}()");
        sb.AppendLine("        {");
        var call = $"new RuntimeObject(Ptr).Invoke(\"{m.MethodName}\", 0)";
        sb.AppendLine($"            var ret = {call};");
        sb.AppendLine($"            return {MarshalReturn(rt, "ret")};");
        sb.AppendLine("        }");
    }

    private static void GenerateSetter(StringBuilder sb, MemberInfo m)
    {
        var pd = string.Join(", ", m.Parameters.Select(p => $"{SimplifyType(p.Type)} @{p.Name}"));
        sb.AppendLine();
        sb.AppendLine($"        public partial void {m.MethodName}({pd})");
        sb.AppendLine("        {");
        if (m.Parameters.Count > 0)
        {
            sb.AppendLine($"            var args = new nint[] {{ {MarshalParam(m.Parameters[0].Type, $"@{m.Parameters[0].Name}")} }};");
        }
        sb.AppendLine($"            new RuntimeObject(Ptr).InvokeVoid(\"{m.MethodName}\", {m.Parameters.Count}{(m.Parameters.Count > 0 ? ", args" : "")});");
        sb.AppendLine("        }");
    }

    private static void GenerateProperty(StringBuilder sb, string name, MemberInfo getter, MemberInfo setter)
    {
        var propName = AsPropertyName(name);
        var ro = SimplifyType(getter.ReturnType);
        var st = getter.IsStatic ? "static " : "";
        sb.AppendLine();
        sb.AppendLine($"        public {st}{ro} {propName}");
        sb.AppendLine("        {");
        sb.AppendLine($"            get => {getter.MethodName}();");
        sb.AppendLine($"            set => {setter.MethodName}(value);");
        sb.AppendLine("        }");
    }

    private static void GeneratePropertyGetOnly(StringBuilder sb, string name, MemberInfo getter)
    {
        var propName = AsPropertyName(name);
        var ro = SimplifyType(getter.ReturnType);
        var st = getter.IsStatic ? "static " : "";
        sb.AppendLine();
        sb.AppendLine($"        public {st}{ro} {propName} => {getter.MethodName}();");
    }

    private static void GeneratePropertySetOnly(StringBuilder sb, string name, MemberInfo setter)
    {
        var propName = AsPropertyName(name);
        var ro = SimplifyType(setter.Parameters[0].Type);
        var st = setter.IsStatic ? "static " : "";
        sb.AppendLine();
        sb.AppendLine($"        public {st}{ro} {propName}");
        sb.AppendLine("        {");
        sb.AppendLine($"            set => {setter.MethodName}(value);");
        sb.AppendLine("        }");
    }

    private static void GenerateAdder(StringBuilder sb, MemberInfo m)
    {
        sb.AppendLine();
        sb.AppendLine($"        public partial void {m.MethodName}({SimplifyType(m.Parameters[0].Type)} @{m.Parameters[0].Name})");
        sb.AppendLine("        {");
        sb.AppendLine($"            new RuntimeObject(Ptr).InvokeVoid(\"{m.MethodName}\", 1, new nint[] {{ (nint)@{m.Parameters[0].Name} }});");
        sb.AppendLine("        }");
    }

    private static void GenerateRemover(StringBuilder sb, MemberInfo m)
    {
        sb.AppendLine();
        sb.AppendLine($"        public partial void {m.MethodName}({SimplifyType(m.Parameters[0].Type)} @{m.Parameters[0].Name})");
        sb.AppendLine("        {");
        sb.AppendLine($"            new RuntimeObject(Ptr).InvokeVoid(\"{m.MethodName}\", 1, new nint[] {{ (nint)@{m.Parameters[0].Name} }});");
        sb.AppendLine("        }");
    }

    private static void GenerateEvent(StringBuilder sb, string name, MemberInfo adder)
    {
        var propName = AsPropertyName(name);
        var et = SimplifyType(adder.Parameters[0].Type);
        sb.AppendLine();
        sb.AppendLine($"        public event {et} {propName}");
        sb.AppendLine("        {");
        sb.AppendLine($"            add => add_{name}(value);");
        sb.AppendLine($"            remove => remove_{name}(value);");
        sb.AppendLine("        }");
    }

    private static string MarshalReturn(string type, string expr)
    {
        return type switch
        {
            "global::System.Void" => "",
            "global::System.IntPtr" or "nint" => expr,
            "global::System.Int32" or "int" => $"(int)(long){expr}",
            "global::System.UInt32" or "uint" => $"(uint)(long){expr}",
            "global::System.Int64" or "long" => $"(long){expr}",
            "global::System.UInt64" or "ulong" => $"(ulong){expr}",
            "global::System.Boolean" or "bool" => $"{expr} != 0",
            "global::System.Byte" or "byte" => $"(byte)(long){expr}",
            "global::System.SByte" or "sbyte" => $"(sbyte)(long){expr}",
            "global::System.Int16" or "short" => $"(short)(long){expr}",
            "global::System.UInt16" or "ushort" => $"(ushort)(long){expr}",
            "global::System.Single" or "float" => $"*(float*)&{expr}",
            "global::System.Double" or "double" => $"*(double*)&{expr}",
            "global::System.String" or "string" => $"new RuntimeString({expr})",
            _ when type.EndsWith("RuntimeString") => $"new RuntimeString({expr})",
            _ when type.EndsWith("RuntimeObject?") => $"{expr} != 0 ? new RuntimeObject({expr}) : null",
            _ when type.EndsWith("RuntimeObject") => $"new RuntimeObject({expr})",
            _ => $"{expr}",
        };
    }

    private static string MarshalParam(string type, string expr)
    {
        var st = SimplifyType(type);
        return type switch
        {
            "global::System.IntPtr" or "nint" => expr,
            "global::System.Int32" or "int" => $"(nint){expr}",
            "global::System.UInt32" or "uint" => $"(nint)(long){expr}",
            "global::System.Int64" or "long" => $"(nint){expr}",
            "global::System.UInt64" or "ulong" => $"(nint)(long){expr}",
            "global::System.Boolean" or "bool" => $"{expr} ? (nint)1 : 0",
            "global::System.Byte" or "byte" => $"(nint){expr}",
            "global::System.SByte" or "sbyte" => $"(nint){expr}",
            "global::System.Int16" or "short" => $"(nint){expr}",
            "global::System.UInt16" or "ushort" => $"(nint){expr}",
            "global::System.Single" or "float" => $"*(nint*)&{expr}",
            "global::System.Double" or "double" => $"*(nint*)&{expr}",
            "global::System.String" or "string" => $"RuntimeString.New({expr}).Ptr",
            _ when type.EndsWith("RuntimeObject") => $"{expr}.Ptr",
            _ when type.EndsWith("RuntimeString") => $"{expr}.Ptr",
            _ when type.EndsWith("UnmanagedObject") => $"{expr}.Ptr",
            _ => $"RuntimeBox.Box<{st}>({expr})",
        };
    }

    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string SimplifyType(string type)
    {
        if (type == "global::System.IntPtr") return "nint";
        if (type == "global::System.UIntPtr") return "nuint";
        if (type == "global::System.Void") return "void";
        if (type == "global::System.Int32") return "int";
        if (type == "global::System.UInt32") return "uint";
        if (type == "global::System.Int64") return "long";
        if (type == "global::System.UInt64") return "ulong";
        if (type == "global::System.Boolean") return "bool";
        if (type == "global::System.Byte") return "byte";
        if (type == "global::System.SByte") return "sbyte";
        if (type == "global::System.Int16") return "short";
        if (type == "global::System.UInt16") return "ushort";
        if (type == "global::System.Single") return "float";
        if (type == "global::System.Double") return "double";
        if (type == "global::System.Char") return "char";
        if (type == "global::System.String") return "string";
        if (type.StartsWith("global::")) return type.Substring(8);
        return type;
    }
}
